# Generated by Django 5.0.6 on 2024-07-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_review_comment_alter_product_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(default='shop/images/p3.png', upload_to='shop/images'),
        ),
    ]
