# Generated by Django 5.0.6 on 2024-07-09 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_wishlist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='image',
        ),
    ]
